name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
    - uses: bahmutov/npm-install@v1
    - name: If this step fails run 'npm run lint' and 'npm run format' then commit again.
      run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        $PACKAGE_MANAGER run lint:check
        $PACKAGE_MANAGER run format:check
  test_node:
    runs-on: ${{ matrix.os }}
    needs: test_lint
    strategy:
      matrix:
        node: [ '15', '14', '12' ]
        os: [ windows-latest, ubuntu-latest ]
    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - name: Tell if project is using npm or yarn
      id: step1
      uses: garronej/ts-ci@v1.1.2
      with: 
        action_name: tell_if_project_uses_npm_or_yarn
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node }}
    - uses: bahmutov/npm-install@v1
    - if: steps.step1.outputs.npm_or_yarn == 'yarn'
      run: |
        yarn build
        yarn test:node
    - if: steps.step1.outputs.npm_or_yarn == 'npm'
      run: |
        npm run build
        npm test:node
  test_deno:
    runs-on: ubuntu-latest
    needs: test_lint
    name: test with Deno
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/deno
        key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
        restore-keys: |
           deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
           deno-${{ runner.os }}-
           deno-
    - uses: denolib/setup-deno@master
      with:
        deno-version: v1.x
    - run: deno --version
    - uses: bahmutov/npm-install@v1
    - run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        $PACKAGE_MANAGER run build
        $PACKAGE_MANAGER run test:deno

  check_if_version_upgraded:
    name: Check if version upgrade
    # We run this only if it's a push on the default branch or if it's a PR from a 
    # branch (meaning not a PR from a fork). It would be more straightforward to test if secrets.NPM_TOKEN is 
    # defined but GitHub Action don't allow it yet.
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login 
    runs-on: ubuntu-latest
    needs: 
      - test_node
      - test_deno
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
      is_release_beta: ${{steps.step1.outputs.is_release_beta }}
    steps:
    - uses: garronej/ts-ci@v1.1.2
      id: step1
      with: 
        action_name: is_package_json_version_upgraded
        branch: ${{ github.head_ref || github.ref }}

  publish:
    runs-on: ubuntu-latest
    if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    needs: 
      - check_if_version_upgraded
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - run: rm -r .github
    - run: |
        git branch -d latest || true
        git push origin :latest || true
    - run: |
        git branch latest
        git checkout latest
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '15'
        registry-url: https://registry.npmjs.org/
    - uses: bahmutov/npm-install@v1
    - run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        $PACKAGE_MANAGER run build
    - run: npx -y -p denoify@0.6.5 denoify_enable_short_npm_import_path
      env:
        DRY_RUN: "0"
    - run: |
        if [ "$(npm show . version)" = "$VERSION" ]; then
          echo "This version is already published"
          exit 0
        fi
        if [ "$NODE_AUTH_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
    - run: |
        git config --global user.name "actions"
        git config --global user.email actions@example.com
        git add -A
        git commit -am "Enabling shorter import paths"
        git push origin latest
    - uses: garronej/action-gh-release@v0.2.0
      with:
        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
        target_commitish: latest
        generate_release_notes: true
        draft: false
        prerelease: ${{ needs.check_if_version_upgraded.outputs.is_release_beta == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

