name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '14', '15' ,'16', '17' ]
        os: [ windows-latest, ubuntu-latest ]
    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - uses: bahmutov/npm-install@v1
    - run: yarn build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - run: yarn test:node
  test_deno:
    runs-on: ubuntu-latest
    name: test with Deno
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '15'
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
        restore-keys: |
           deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
           deno-${{ runner.os }}-
           deno-
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno --version
    - uses: bahmutov/npm-install@v1
    - run: yarn build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - run: yarn test:deno
  check_if_version_upgraded:
    name: Check if version upgrade
    # We run this only if it's a push on the default branch or if it's a PR from a 
    # branch (meaning not a PR from a fork). It would be more straightforward to test if secrets.NPM_TOKEN is 
    # defined but GitHub Action don't allow it yet.
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login 
    runs-on: ubuntu-latest
    needs: 
      - test_node
      - test_deno
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
      is_pre_release: ${{steps.step1.outputs.is_pre_release }}
    steps:
    - uses: garronej/ts-ci@v2.1.0
      id: step1
      with: 
        action_name: is_package_json_version_upgraded
        branch: ${{ github.head_ref || github.ref }}

  publish:
    runs-on: ubuntu-latest
    needs: 
      - check_if_version_upgraded
    # We create a release only if the version have been upgraded and we are on the main branch
    # or if we are on a branch of the repo that has an PR open on main.
    if: |
      needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true' &&
      (
        github.event_name == 'push' ||
        needs.check_if_version_upgraded.outputs.is_pre_release == 'true'
      )
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - run: rm -r .github
    - name: Remove tmp_branch if it exists
      run: git push origin :tmp_branch || true
    - run: git checkout -b tmp_branch
    - uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
    - uses: bahmutov/npm-install@v1
    - run: yarn build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - run: |
        npx -y -p denoify@1.5.2 enable_short_npm_import_path
        npx -y -p denoify@1.5.2 remove_deno_dist_from_gitignore
      env:
        DRY_RUN: "0"
    - run: |
        if [ "$(npm show . version)" = "$VERSION" ]; then
          echo "This version is already published"
          exit 0
        fi
        if [ "$NODE_AUTH_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        EXTRA_ARGS=""
        if [ "$IS_PRE_RELEASE" = "true" ]; then
            EXTRA_ARGS="--tag next"
        fi
        npm publish $EXTRA_ARGS
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
        IS_PRE_RELEASE: ${{ needs.check_if_version_upgraded.outputs.is_pre_release }}
    - run: |
        git config --global user.name "actions"
        git config --global user.email actions@github.com
        git add -A
        git commit -am "Adding deno distribution files and moving files from /dist to /"
        git push origin tmp_branch
    - uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
        target_commitish: tmp_branch
        generate_release_notes: false
        draft: false
        prerelease: ${{ needs.check_if_version_upgraded.outputs.is_pre_release == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Remove tmp_branch
      run: git push origin :tmp_branch
