name: ci
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:

  test_node:
    runs-on: ubuntu-latest
    if: ${{ !github.event.created }}
    strategy:
      matrix:
        node: [ '13', '12', '11', '10', '8' ]
    name: Test with Node v${{ matrix.node }}
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build
    - run: npm run test:node

  test_deno:
    runs-on: ubuntu-latest
    if: ${{ !github.event.created }}
    name: test with Deno
    steps: 

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/deno
        key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
        restore-keys: |
           deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
           deno-${{ runner.os }}-
           deno-
    - uses: denolib/setup-deno@master
      with:
        deno-version: 1.x
    - run: npm ci
    - run: npm run build
    - run: npm run test:deno

  trigger_publish:
    name: Trigger publish.yaml workflow if package.json version updated ( and secrets.PAT is set ).
    runs-on: ubuntu-latest
    env:
      PAT: ${{secrets.PAT}}
    if: github.event_name == 'push' && github.event.head_commit.author.name != 'denoify_ci'
    needs:
      - test_node
      - test_deno
    steps:

    - name: Get version on master
      id: v_master
      uses: garronej/github_actions_toolkit@v1.2
      with: 
        action_name: get_package_json_version
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        branch: master
        compare_to_version: '0.0.0'

    - name: Get version on develop
      id: v_develop
      uses: garronej/github_actions_toolkit@v1.2
      with: 
        action_name: get_package_json_version
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        branch: ${{ github.sha }}
        compare_to_version: ${{steps.v_master.outputs.version || '0.0.0'}}

    - name: 'Trigger the ''publish'' workflow' 
      if: ${{ !!env.PAT && steps.v_develop.outputs.compare_result == '1' }}
      uses: garronej/github_actions_toolkit@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        action_name: dispatch_event
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        event_type: publish
        client_payload_json: |
          ${{
            format(
              '{{"from_version":"{0}","to_version":"{1}","repo":"{2}"}}',
              steps.v_master.outputs.version,
              steps.v_develop.outputs.version,
              github.event.repository.name
            )
          }}
